name: ff-env
channels:
  - conda-forge
dependencies:
  - black
  - cutde
  - cartopy
  - filelock
  - isort
  - matplotlib
  - mypy
  - netcdf4
  - obspy
  - pip
  - pip-audit
  - pydantic
  - pygmt
  - pytest
  - pytest-cov
  - python=3.10
  - ratelimiter
  - scipy
  - shapely
  - tornado>=6.5.8
  - typer
  - pip:
      - pyrocko
      - poethepoet
