name: ff-env
channels:
  - conda-forge
dependencies:
  - cutde
  - cartopy
  - matplotlib
  - netcdf4
  - obspy
  - pip
  - pydantic
  - pygmt
  - python=3.10
  - ratelimiter
  - scipy
  - shapely
  - typer
  - pip:
    - pyrocko
